# Generated by Django 4.2 on 2023-10-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('age', models.IntegerField(default=20)),
                ('test_task_mark', models.IntegerField()),
                ('interview_mark', models.IntegerField()),
                ('salary_exp', models.IntegerField()),
            ],
        ),
    ]
