# Generated by Django 4.2 on 2023-10-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_candidate_interview_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(max_length=500)),
                ('min_expirience', models.IntegerField()),
            ],
        ),
    ]
