# Generated by Django 4.2 on 2023-10-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Main.position'),
            preserve_default=False,
        ),
    ]
