# Generated by Django 4.2 on 2023-11-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_skill_candidateskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='Main.skill'),
        ),
        migrations.DeleteModel(
            name='CandidateSkill',
        ),
    ]
